import type { GalleryImage } from '@/types';

/** All gallery artwork in public/gallery — used as fallback if DB is empty */
export const ALL_GALLERY_IMAGES: GalleryImage[] = [
  {
    _id: 'gallery-1',
    categoryId: 'mystical-paintings',
    title: 'The Hidden Archway',
    description: 'A shadowed passage where mystery and architecture converge in deep crimson and gold.',
    imageUrl: '/gallery/mystical-archway.jpg',
    altText: 'Mystical archway painting in crimson and gold tones',
    medium: 'Acrylic on Canvas',
    dimensions: '24" x 36"',
    year: '2024',
    availability: 'contact',
    isFeatured: true,
    isPublished: true,
    displayOrder: 0,
  },
  {
    _id: 'gallery-2',
    categoryId: 'mystical-paintings',
    title: 'Crimson Passage',
    description: 'Expressive brushwork and layered pigment evoke a narrative of intrigue and revelation.',
    imageUrl: '/gallery/crimson-abstract.jpg',
    altText: 'Abstract crimson and black mystical painting',
    medium: 'Mixed Media on Canvas',
    dimensions: '30" x 40"',
    year: '2023',
    availability: 'contact',
    isFeatured: true,
    isPublished: true,
    displayOrder: 1,
  },
  {
    _id: 'gallery-3',
    categoryId: 'mystical-paintings',
    title: 'Mystery at Dusk',
    description: 'Atmospheric tones and textured surfaces suggest a story unfolding at twilight.',
    imageUrl: '/gallery/mystery-at-dusk.jpg',
    altText: 'Dark atmospheric mystical artwork',
    medium: 'Oil on Canvas',
    dimensions: '20" x 24"',
    year: '2024',
    availability: 'contact',
    isFeatured: true,
    isPublished: true,
    displayOrder: 2,
  },
  {
    _id: 'gallery-4',
    categoryId: 'original-paintings',
    title: 'Golden Spiral',
    description: 'Geometric motifs and luminous gold accents create a sense of timeless movement.',
    imageUrl: '/gallery/golden-spiral.jpg',
    altText: 'Original painting with golden spiral motifs',
    medium: 'Acrylic on Canvas',
    dimensions: '18" x 24"',
    year: '2024',
    availability: 'available',
    isFeatured: true,
    isPublished: true,
    displayOrder: 3,
  },
  {
    _id: 'gallery-5',
    categoryId: 'original-paintings',
    title: 'Velvet Shadows',
    description: 'Rich, velvety darks contrast with warm highlights in this collector favourite.',
    imageUrl: '/gallery/velvet-shadows.jpg',
    altText: 'Original painting with deep velvet shadows',
    medium: 'Acrylic on Canvas',
    dimensions: '24" x 30"',
    year: '2023',
    availability: 'contact',
    isFeatured: true,
    isPublished: true,
    displayOrder: 4,
  },
  {
    _id: 'gallery-6',
    categoryId: 'original-paintings',
    title: 'Atmospheric Reverie',
    description: 'A contemplative landscape rendered in moody, cinematic tones.',
    imageUrl: '/gallery/atmospheric-landscape.jpg',
    altText: 'Atmospheric landscape original painting',
    medium: 'Oil on Canvas',
    dimensions: '22" x 28"',
    year: '2022',
    availability: 'contact',
    isFeatured: false,
    isPublished: true,
    displayOrder: 5,
  },
  {
    _id: 'gallery-7',
    categoryId: 'original-paintings',
    title: 'Architectural Dreams',
    description: 'Structural forms dissolve into imagination — a hallmark of the mystery art style.',
    imageUrl: '/gallery/architectural-dreams.jpg',
    altText: 'Architectural dreamscape original painting',
    medium: 'Acrylic on Canvas',
    dimensions: '26" x 34"',
    year: '2024',
    availability: 'contact',
    isFeatured: false,
    isPublished: true,
    displayOrder: 6,
  },
  {
    _id: 'gallery-8',
    categoryId: 'murals',
    title: 'Urban Mural Vision',
    description: 'Large-scale mural concept bringing narrative art into architectural space.',
    imageUrl: '/gallery/mural-wall.jpg',
    altText: 'Large-scale mural artwork on wall',
    medium: 'Mural — Acrylic',
    dimensions: 'Custom Scale',
    year: '2024',
    availability: 'contact',
    isFeatured: true,
    isPublished: true,
    displayOrder: 7,
  },
  {
    _id: 'gallery-9',
    categoryId: 'murals',
    title: 'Echoes in Gold',
    description: 'Sweeping mural composition with gold leaf accents and dramatic contrast.',
    imageUrl: '/gallery/echoes-in-gold.jpg',
    altText: 'Mural with gold accents and dramatic lighting',
    medium: 'Mural — Mixed Media',
    dimensions: 'Custom Scale',
    year: '2023',
    availability: 'contact',
    isFeatured: false,
    isPublished: true,
    displayOrder: 8,
  },
  {
    _id: 'gallery-10',
    categoryId: 'commissioned-work',
    title: "Collector's Selection",
    description: 'A commissioned piece designed to anchor a private collection with mystery and warmth.',
    imageUrl: '/gallery/gallery-collection.jpg',
    altText: 'Commissioned artwork displayed in gallery setting',
    medium: 'Acrylic on Canvas',
    dimensions: '30" x 36"',
    year: '2024',
    availability: 'sold',
    isFeatured: true,
    isPublished: true,
    displayOrder: 9,
  },
  {
    _id: 'gallery-11',
    categoryId: 'studio-and-process',
    title: 'Inside the Studio',
    description: 'The creative environment where paintings, murals, and stories take shape.',
    imageUrl: '/gallery/studio-gallery.jpg',
    altText: 'Artist studio with framed paintings and creative tools',
    medium: 'Studio Documentation',
    dimensions: '—',
    year: '2024',
    availability: 'not_available',
    isFeatured: true,
    isPublished: true,
    displayOrder: 10,
  },
];
